package day7

import kotlin.test.Test
import kotlin.test.assertEquals

class Test {
    private val input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent().lines()

    @Test
    fun part1Example() {
        val tachyonManifold = TachyonManifold.parse(input)
        val totalSplits = tachyonManifold.totalSplits()
        assertEquals(21, totalSplits)
    }
}